[skin]
    description = skin inspired by Dos Navigator (16 color)

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ═
    dvert = ║
    dlefttop = ╔
    drighttop = ╗
    dleftbottom = ╚
    drightbottom = ╝
    dtopmiddle = ╤
    dbottommiddle = ╧
    dleftmiddle = ╟
    drightmiddle = ╢

[core]
    _default_ = lightgray;gray
    selected = black;cyan
    marked = yellow;gray
    markselect = yellow;cyan
    gauge = white;black
    input = white;black
    inputunchanged = lightgray;black
    inputmark = yellow;black
    disabled = gray;lightgray
    reverse = gray;lightgray
    commandlinemark = black;lightgray
    header = white;gray
    inputhistory = white;black
    commandhistory =
    shadow = black;black

[dialog]
    _default_ = black;lightgray
    dfocus = white;gray
    dhotnormal = yellow;lightgray
    dhotfocus = yellow;gray
    dtitle = black;lightgray

[error]
    _default_ = white;red
    errdfocus = black;lightgray
    errdhotnormal = yellow;red
    errdhotfocus = yellow;lightgray
    errdtitle = yellow;red

[filehighlight]
    directory = white;
    executable = brightgreen;
    symlink = brightcyan;
    hardlink =
    stalelink = brightred;
    device = brightmagenta;
    special = brightgreen;
    core = red;
    temp = lightgray;
    archive = brightmagenta;
    doc = brown;
    source = cyan;
    media = green;
    graph = brightcyan;
    database = brightred;

[menu]
    _default_ = black;lightgray
    menusel = black;green
    menuhot = red;lightgray
    menuhotsel = red;green
    menuinactive = gray;lightgray

[popupmenu]
    _default_ = black;lightgray
    menusel = black;green
    menutitle = black;lightgray

[buttonbar]
    hotkey = red;lightgray
    button = black;lightgray

[statusbar]
    _default_ = black;lightgray

[help]
    _default_ = yellow;cyan
    helpitalic = brightgreen;cyan
    helpbold = white;cyan
    helplink = black;lightgray
    helpslink = yellow;black
    helptitle = blue;cyan

[editor]
    _default_ = lightgray;gray
    editbold = yellow;green
    editmarked = black;cyan
    editwhitespace = brightblue;gray
    editlinestate = white;cyan
    bookmark = white;red
    bookmarkfound = black;green
    editrightmargin = brightblue;black
#    editbg =
#    editframe =
    editframeactive = white;
    editframedrag = brightcyan;

[viewer]
    _default_ = lightgray;gray
    viewbold = yellow;gray
    viewunderline = brightred;gray
    viewselected = black;lightgray

[diffviewer]
    added = white;green
    changedline = blue;cyan
    changednew = red;cyan
    changed = white;cyan
    removed = white;red
    error = red;lightgray

[widget-panel]
    sort-up-char = ↑
    sort-down-char = ↓
    hiddenfiles-show-char = ⋅
    hiddenfiles-hide-char = •
    history-prev-item-char = «
    history-next-item-char = »
    history-show-list-char = ^
    filename-scroll-left-char = «
    filename-scroll-right-char = »

[widget-editor]
    window-state-char = ↕
    window-close-char = ✕
