[skin]
    description = skin inspired by Far Manager
    truecolors = true

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ═
    dvert = ║
    dlefttop = ╔
    drighttop = ╗
    dleftbottom = ╚
    drightbottom = ╝
    dtopmiddle = ╤
    dbottommiddle = ╧
    dleftmiddle = ╟
    drightmiddle = ╢

[core]
    _default_ = #00ffff;#000080
    selected = #000000;#008080
    marked = #ffff55;#000080
    markselect = #ffff55;#008080
    gauge = #ffffff;#000000
    input = #000000;#008080
    inputunchanged = #c0c0c0;#008080
    inputmark = #00aaaa;#000000
    disabled = #808080;#c0c0c0
    reverse = #000000;#008080
    commandlinemark = #000000;#c0c0c0
    header = #ffff55;#000080
    inputhistory = #000000;#c0c0c0
    commandhistory =
    shadow = #00a0a0;#000000

[dialog]
    _default_ = #000000;#c0c0c0
    dfocus = #000000;#808080
    dhotnormal = #ffff00;#c0c0c0
    dhotfocus = #ffff00;#808080
    dtitle = #000000;#c0c0c0

[error]
    _default_ = #ffffff;#aa0000
    errdfocus = #000000;#c0c0c0
    errdhotnormal = #ffff55;#aa0000
    errdhotfocus = #ffff55;#c0c0c0
    errdtitle = #ffff55;#aa0000

[filehighlight]
    directory = #ffffff;
    executable = #55ff55;
    symlink = #c0c0c0;
    hardlink =
    stalelink = #ff5555;
    device = #ff55ff;
    special = #00ffbb;
    core = #aa0000;
    temp = #808080;
    archive = #ff55ff;
    doc = #aa5500;
    source = #00aaaa;
    media = #00aa00;
    graph = #55ffff;
    database = #ff5555;

[menu]
    _default_ = #ffffff;#008080
    menusel = #ffffff;#000000
    menuhot = #ffff55;#008080
    menuhotsel = #ffff55;#000000
    menuinactive = #000000;#008080

[popupmenu]
    _default_ = #ffffff;#008080
    menusel = #ffffff;#000000
    menutitle = #ffffff;#008080

[buttonbar]
    hotkey = #c0c0c0;#000000
    button = #000000;#008080

[statusbar]
    _default_ = #000000;#008080

[help]
    _default_ = #000000;#c0c0c0
    helpitalic = #aa0000;#c0c0c0
    helpbold = #0000aa;#c0c0c0
    helplink = #000000;#008080
    helpslink = #ffff55;#000080
    helptitle = #0000aa;#c0c0c0

[editor]
    _default_ = #00ffff;#000080
    editbold = #ffff55;#00aa00
    editmarked = #000000;#008080
    editwhitespace = #5555ff;#000080
    editlinestate = #ffffff;#008080
    bookmark = #ffffff;#aa0000
    bookmarkfound = #000000;#00aa00
    editrightmargin = #5555ff;#000000
#    editbg =
#    editframe =
    editframeactive = #c0c0c0;
    editframedrag = #00aaaa;

[viewer]
    _default_ = #00ffff;#000080
    viewbold = #ffff55;#000080
    viewunderline = #ff5555;#000080
    viewselected = #ffff55;#008080

[diffviewer]
    added = #ffffff;#00aa00
    changedline = #0000aa;#008080
    changednew = #aa0000;#008080
    changed = #ffffff;#008080
    removed = #ffffff;#aa0000
    error = #aa0000;#c0c0c0

[widget-panel]
    sort-up-char = ↑
    sort-down-char = ↓
    hiddenfiles-show-char = ⋅
    hiddenfiles-hide-char = •
    history-prev-item-char = «
    history-next-item-char = »
    history-show-list-char = ^
    filename-scroll-left-char = «
    filename-scroll-right-char = »

[widget-editor]
    window-state-char = ↕
    window-close-char = ✕
