[skin]
    description = Gruvbox Light color scheme
    truecolors = true

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ═
    dvert = ║
    dlefttop = ╔
    drighttop = ╗
    dleftbottom = ╚
    drightbottom = ╝
    dtopmiddle = ╤
    dbottommiddle = ╧
    dleftmiddle = ╟
    drightmiddle = ╢

[core]
    _default_ = #3c3836;#fbf1c7
    selected = #3c3836;#ebdbb2
    marked = #b57614;#fbf1c7
    markselect = #b57614;#ebdbb2
    gauge = #79740e;#fbf1c7
    input = #3c3836;#ebdbb2
    inputunchanged = #7c6f64;#ebdbb2
    inputmark = #fbf1c7;#076678
    disabled = #928374;#fbf1c7
    reverse = #fbf1c7;#3c3836
    commandlinemark = #fbf1c7;#076678
    header = #076678;#fbf1c7
    inputhistory = #3c3836;#ebdbb2
    commandhistory =
    shadow = #d5c4a1;#d5c4a1

[dialog]
    _default_ = #3c3836;#ebdbb2
    dfocus = #fbf1c7;#076678
    dhotnormal = #9d0006;#ebdbb2
    dhotfocus = #fbf1c7;#9d0006
    dtitle = #076678;#ebdbb2

[error]
    _default_ = #fbf1c7;#9d0006
    errdfocus = #3c3836;#af3a03
    errdhotnormal = #b57614;#9d0006
    errdhotfocus = #3c3836;#b57614
    errdtitle = #b57614;#9d0006

[filehighlight]
    directory = #076678;
    executable = #79740e;
    symlink = #928374;
    hardlink =
    stalelink = #9d0006;
    device = #8f3f71;
    special = #af3a03;
    core = #9d0006;
    temp = #a89984;
    archive = #8f3f71;
    doc = #b57614;
    source = #427b58;
    media = #af3a03;
    graph = #076678;
    database = #9d0006;

[menu]
    _default_ = #3c3836;#ebdbb2
    menusel = #3c3836;#d5c4a1
    menuhot = #9d0006;#ebdbb2
    menuhotsel = #9d0006;#d5c4a1
    menuinactive = #928374;#ebdbb2

[popupmenu]
    _default_ = #3c3836;#ebdbb2
    menusel = #3c3836;#d5c4a1
    menutitle = #076678;#ebdbb2

[buttonbar]
    hotkey = #928374;#fbf1c7
    button = #3c3836;#ebdbb2

[statusbar]
    _default_ = #3c3836;#ebdbb2

[help]
    _default_ = #3c3836;#ebdbb2
    helpitalic = #b57614;#ebdbb2
    helpbold = #79740e;#ebdbb2
    helplink = #076678;#ebdbb2
    helpslink = #fbf1c7;#076678
    helptitle = #9d0006;#ebdbb2

[editor]
    _default_ = #3c3836;#fbf1c7
    editbold = #79740e;#fbf1c7
    editmarked = #3c3836;#ebdbb2
    editwhitespace = #d5c4a1;#fbf1c7
    editlinestate = #928374;#ebdbb2
    bookmark = #fbf1c7;#9d0006
    bookmarkfound = #fbf1c7;#79740e
    editrightmargin = #ebdbb2;#fbf1c7
#    editbg =
#    editframe =
    editframeactive = #076678;
    editframedrag = #9d0006;

[viewer]
    _default_ = #3c3836;#fbf1c7
    viewbold = #79740e;#fbf1c7
    viewunderline = #076678;#fbf1c7
    viewselected = #3c3836;#ebdbb2

[diffviewer]
    added = #79740e;#fbf1c7
    changedline = #076678;#fbf1c7
    changednew = #af3a03;#fbf1c7
    changed = #b57614;#fbf1c7
    removed = #9d0006;#fbf1c7
    error = #fbf1c7;#9d0006

[widget-panel]
    sort-up-char = ↑
    sort-down-char = ↓
    hiddenfiles-show-char = ⋅
    hiddenfiles-hide-char = •
    history-prev-item-char = «
    history-next-item-char = »
    history-show-list-char = ^
    filename-scroll-left-char = «
    filename-scroll-right-char = »

[widget-editor]
    window-state-char = ↕
    window-close-char = ✕
