[skin]
    description = Gruvbox Dark color scheme
    truecolors = true

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ═
    dvert = ║
    dlefttop = ╔
    drighttop = ╗
    dleftbottom = ╚
    drightbottom = ╝
    dtopmiddle = ╤
    dbottommiddle = ╧
    dleftmiddle = ╟
    drightmiddle = ╢

[core]
    _default_ = #ebdbb2;#282828
    selected = #ebdbb2;#3c3836
    marked = #fabd2f;#282828
    markselect = #fabd2f;#3c3836
    gauge = #b8bb26;#282828
    input = #ebdbb2;#3c3836
    inputunchanged = #a89984;#3c3836
    inputmark = #282828;#fabd2f
    disabled = #928374;#282828
    reverse = #282828;#ebdbb2
    commandlinemark = #282828;#fabd2f
    header = #83a598;#282828
    inputhistory = #ebdbb2;#3c3836
    commandhistory =
    shadow = #1d2021;#1d2021

[dialog]
    _default_ = #ebdbb2;#3c3836
    dfocus = #282828;#83a598
    dhotnormal = #fb4934;#3c3836
    dhotfocus = #282828;#fb4934
    dtitle = #83a598;#3c3836

[error]
    _default_ = #ebdbb2;#fb4934
    errdfocus = #282828;#fe8019
    errdhotnormal = #fabd2f;#fb4934
    errdhotfocus = #282828;#fabd2f
    errdtitle = #fabd2f;#fb4934

[filehighlight]
    directory = #83a598;
    executable = #b8bb26;
    symlink = #928374;
    hardlink =
    stalelink = #fb4934;
    device = #d3869b;
    special = #fe8019;
    core = #fb4934;
    temp = #a89984;
    archive = #d3869b;
    doc = #fabd2f;
    source = #8ec07c;
    media = #fe8019;
    graph = #83a598;
    database = #fb4934;

[menu]
    _default_ = #ebdbb2;#3c3836
    menusel = #ebdbb2;#504945
    menuhot = #fb4934;#3c3836
    menuhotsel = #fb4934;#504945
    menuinactive = #928374;#3c3836

[popupmenu]
    _default_ = #ebdbb2;#3c3836
    menusel = #ebdbb2;#504945
    menutitle = #83a598;#3c3836

[buttonbar]
    hotkey = #928374;#282828
    button = #ebdbb2;#3c3836

[statusbar]
    _default_ = #ebdbb2;#3c3836

[help]
    _default_ = #ebdbb2;#3c3836
    helpitalic = #fabd2f;#3c3836
    helpbold = #b8bb26;#3c3836
    helplink = #83a598;#3c3836
    helpslink = #282828;#83a598
    helptitle = #fb4934;#3c3836

[editor]
    _default_ = #ebdbb2;#282828
    editbold = #b8bb26;#282828
    editmarked = #ebdbb2;#3c3836
    editwhitespace = #504945;#282828
    editlinestate = #928374;#3c3836
    bookmark = #ebdbb2;#fb4934
    bookmarkfound = #282828;#b8bb26
    editrightmargin = #3c3836;#282828
#    editbg =
#    editframe =
    editframeactive = #83a598;
    editframedrag = #fb4934;

[viewer]
    _default_ = #ebdbb2;#282828
    viewbold = #b8bb26;#282828
    viewunderline = #83a598;#282828
    viewselected = #ebdbb2;#3c3836

[diffviewer]
    added = #b8bb26;#282828
    changedline = #83a598;#282828
    changednew = #fe8019;#282828
    changed = #fabd2f;#282828
    removed = #fb4934;#282828
    error = #ebdbb2;#fb4934

[widget-panel]
    sort-up-char = ↑
    sort-down-char = ↓
    hiddenfiles-show-char = ⋅
    hiddenfiles-hide-char = •
    history-prev-item-char = «
    history-next-item-char = »
    history-show-list-char = ^
    filename-scroll-left-char = «
    filename-scroll-right-char = »

[widget-editor]
    window-state-char = ↕
    window-close-char = ✕
