[skin]
    description = macOS Light color scheme
    truecolors = true

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ═
    dvert = ║
    dlefttop = ╔
    drighttop = ╗
    dleftbottom = ╚
    drightbottom = ╝
    dtopmiddle = ╤
    dbottommiddle = ╧
    dleftmiddle = ╟
    drightmiddle = ╢

[core]
    _default_ = #000000;#ffffff
    selected = #ffffff;#007aff
    marked = #007aff;#ffffff
    markselect = #ffffff;#005ec4
    gauge = #ffffff;#007aff
    input = #000000;#ffffff
    inputunchanged = #8e8e93;#ffffff
    inputmark = #000000;#b3d7ff
    disabled = #8e8e93;#f6f6f6
    reverse = #ffffff;#000000
    commandlinemark = #000000;#b3d7ff
    header = #000000;#ececec
    inputhistory = #000000;#ffffff
    commandhistory =
    shadow = #c0c0c0;#c0c0c0

[dialog]
    _default_ = #000000;#f6f6f6
    dfocus = #ffffff;#007aff
    dhotnormal = #007aff;#f6f6f6
    dhotfocus = #ffffff;#007aff
    dtitle = #000000;#f6f6f6

[error]
    _default_ = #ffffff;#ff3b30
    errdfocus = #000000;#f6f6f6
    errdhotnormal = #ffcc00;#ff3b30
    errdhotfocus = #ffcc00;#f6f6f6
    errdtitle = #ffffff;#ff3b30

[filehighlight]
    directory = #007aff;
    executable = #28cd41;
    symlink = #8e8e93;
    hardlink =
    stalelink = #ff3b30;
    device = #ff9500;
    special = #af52de;
    core = #ff3b30;
    temp = #8e8e93;
    archive = #af52de;
    doc = #007aff;
    source = #28cd41;
    media = #ff2d55;
    graph = #55bef0;
    database = #5856d6;

[menu]
    _default_ = #000000;#f6f6f6
    menusel = #ffffff;#007aff
    menuhot = #007aff;#f6f6f6
    menuhotsel = #ffffff;#007aff
    menuinactive = #8e8e93;#f6f6f6

[popupmenu]
    _default_ = #000000;#ffffff
    menusel = #ffffff;#007aff
    menutitle = #000000;#ffffff

[buttonbar]
    hotkey = #007aff;#ececec
    button = #000000;#ececec

[statusbar]
    _default_ = #000000;#ececec

[help]
    _default_ = #000000;#ffffff
    helpitalic = #ff9500;#ffffff
    helpbold = #000000;#ffffff
    helplink = #007aff;#ffffff
    helpslink = #ffffff;#007aff
    helptitle = #000000;#ffffff

[editor]
    _default_ = #000000;#ffffff
    editbold = #007aff;#ffffff
    editmarked = #000000;#b3d7ff
    editwhitespace = #e8e8e8;#ffffff
    editlinestate = #8e8e93;#f6f6f6
    bookmark = #ffffff;#ff3b30
    bookmarkfound = #000000;#28cd41
    editrightmargin = #f6f6f6;#ffffff
#    editbg =
#    editframe =
    editframeactive = #007aff;
    editframedrag = #8e8e93;

[viewer]
    _default_ = #000000;#ffffff
    viewbold = #007aff;#ffffff
    viewunderline = #5856d6;#ffffff
    viewselected = #000000;#b3d7ff

[diffviewer]
    added = #28cd41;#ffffff
    changedline = #007aff;#ffffff
    changednew = #ff9500;#ffffff
    changed = #ffcc00;#ffffff
    removed = #ff3b30;#ffffff
    error = #ffffff;#ff3b30

[widget-panel]
    sort-up-char = ↑
    sort-down-char = ↓
    hiddenfiles-show-char = ⋅
    hiddenfiles-hide-char = •
    history-prev-item-char = «
    history-next-item-char = »
    history-show-list-char = ^
    filename-scroll-left-char = «
    filename-scroll-right-char = »

[widget-editor]
    window-state-char = ↕
    window-close-char = ✕
