[skin]
    description = Monokai Pro Light color scheme
    truecolors = true

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ═
    dvert = ║
    dlefttop = ╔
    drighttop = ╗
    dleftbottom = ╚
    drightbottom = ╝
    dtopmiddle = ╤
    dbottommiddle = ╧
    dleftmiddle = ╟
    drightmiddle = ╢

[core]
    _default_ = #29242a;#faf4f2
    selected = #29242a;#ede7e5
    marked = #cc7a0a;#faf4f2
    markselect = #cc7a0a;#ede7e5
    gauge = #269d69;#faf4f2
    input = #29242a;#ede7e5
    inputunchanged = #918c8e;#ede7e5
    inputmark = #faf4f2;#1c8ca8
    disabled = #a59fa0;#faf4f2
    reverse = #faf4f2;#29242a
    commandlinemark = #faf4f2;#1c8ca8
    header = #1c8ca8;#faf4f2
    inputhistory = #29242a;#ede7e5
    commandhistory =
    shadow = #d3cdcc;#d3cdcc

[dialog]
    _default_ = #29242a;#d3cdcc
    dfocus = #faf4f2;#1c8ca8
    dhotnormal = #e14775;#d3cdcc
    dhotfocus = #faf4f2;#e14775
    dtitle = #1c8ca8;#d3cdcc

[error]
    _default_ = #faf4f2;#e14775
    errdfocus = #29242a;#e16032
    errdhotnormal = #cc7a0a;#e14775
    errdhotfocus = #29242a;#cc7a0a
    errdtitle = #cc7a0a;#e14775

[filehighlight]
    directory = #1c8ca8;
    executable = #269d69;
    symlink = #918c8e;
    hardlink =
    stalelink = #e14775;
    device = #e16032;
    special = #7058be;
    core = #e14775;
    temp = #a59fa0;
    archive = #7058be;
    doc = #cc7a0a;
    source = #269d69;
    media = #e16032;
    graph = #1c8ca8;
    database = #e14775;

[menu]
    _default_ = #29242a;#d3cdcc
    menusel = #29242a;#bfb9ba
    menuhot = #e14775;#d3cdcc
    menuhotsel = #e14775;#bfb9ba
    menuinactive = #a59fa0;#d3cdcc

[popupmenu]
    _default_ = #29242a;#d3cdcc
    menusel = #29242a;#bfb9ba
    menutitle = #1c8ca8;#d3cdcc

[buttonbar]
    hotkey = #918c8e;#faf4f2
    button = #29242a;#d3cdcc

[statusbar]
    _default_ = #29242a;#d3cdcc

[help]
    _default_ = #29242a;#d3cdcc
    helpitalic = #cc7a0a;#d3cdcc
    helpbold = #269d69;#d3cdcc
    helplink = #1c8ca8;#d3cdcc
    helpslink = #faf4f2;#1c8ca8
    helptitle = #e14775;#d3cdcc

[editor]
    _default_ = #29242a;#faf4f2
    editbold = #269d69;#faf4f2
    editmarked = #29242a;#ede7e5
    editwhitespace = #d3cdcc;#faf4f2
    editlinestate = #918c8e;#ede7e5
    bookmark = #faf4f2;#e14775
    bookmarkfound = #faf4f2;#269d69
    editrightmargin = #ede7e5;#faf4f2
#    editbg =
#    editframe =
    editframeactive = #1c8ca8;
    editframedrag = #e14775;

[viewer]
    _default_ = #29242a;#faf4f2
    viewbold = #269d69;#faf4f2
    viewunderline = #1c8ca8;#faf4f2
    viewselected = #29242a;#ede7e5

[diffviewer]
    added = #269d69;#faf4f2
    changedline = #1c8ca8;#faf4f2
    changednew = #e16032;#faf4f2
    changed = #cc7a0a;#faf4f2
    removed = #e14775;#faf4f2
    error = #faf4f2;#e14775

[widget-panel]
    sort-up-char = ↑
    sort-down-char = ↓
    hiddenfiles-show-char = ⋅
    hiddenfiles-hide-char = •
    history-prev-item-char = «
    history-next-item-char = »
    history-show-list-char = ^
    filename-scroll-left-char = «
    filename-scroll-right-char = »

[widget-editor]
    window-state-char = ↕
    window-close-char = ✕
