[skin]
    description = Monokai Pro color scheme
    truecolors = true

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ═
    dvert = ║
    dlefttop = ╔
    drighttop = ╗
    dleftbottom = ╚
    drightbottom = ╝
    dtopmiddle = ╤
    dbottommiddle = ╧
    dleftmiddle = ╟
    drightmiddle = ╢

[core]
    _default_ = #fcfcfa;#2d2a2e
    selected = #fcfcfa;#403e41
    marked = #ffd866;#2d2a2e
    markselect = #ffd866;#403e41
    gauge = #a9dc76;#2d2a2e
    input = #fcfcfa;#403e41
    inputunchanged = #939293;#403e41
    inputmark = #2d2a2e;#ffd866
    disabled = #727072;#2d2a2e
    reverse = #2d2a2e;#fcfcfa
    commandlinemark = #2d2a2e;#ffd866
    header = #78dce8;#2d2a2e
    inputhistory = #fcfcfa;#403e41
    commandhistory =
    shadow = #19181a;#19181a

[dialog]
    _default_ = #fcfcfa;#403e41
    dfocus = #2d2a2e;#78dce8
    dhotnormal = #ff6188;#403e41
    dhotfocus = #2d2a2e;#ff6188
    dtitle = #78dce8;#403e41

[error]
    _default_ = #fcfcfa;#ff6188
    errdfocus = #2d2a2e;#fc9867
    errdhotnormal = #ffd866;#ff6188
    errdhotfocus = #2d2a2e;#ffd866
    errdtitle = #ffd866;#ff6188

[filehighlight]
    directory = #78dce8;
    executable = #a9dc76;
    symlink = #939293;
    hardlink =
    stalelink = #ff6188;
    device = #fc9867;
    special = #ab9df2;
    core = #ff6188;
    temp = #727072;
    archive = #ab9df2;
    doc = #ffd866;
    source = #a9dc76;
    media = #fc9867;
    graph = #78dce8;
    database = #ff6188;

[menu]
    _default_ = #fcfcfa;#403e41
    menusel = #fcfcfa;#5b595c
    menuhot = #ff6188;#403e41
    menuhotsel = #ff6188;#5b595c
    menuinactive = #727072;#403e41

[popupmenu]
    _default_ = #fcfcfa;#403e41
    menusel = #fcfcfa;#5b595c
    menutitle = #78dce8;#403e41

[buttonbar]
    hotkey = #939293;#2d2a2e
    button = #fcfcfa;#403e41

[statusbar]
    _default_ = #fcfcfa;#403e41

[help]
    _default_ = #fcfcfa;#403e41
    helpitalic = #ffd866;#403e41
    helpbold = #a9dc76;#403e41
    helplink = #78dce8;#403e41
    helpslink = #2d2a2e;#78dce8
    helptitle = #ff6188;#403e41

[editor]
    _default_ = #fcfcfa;#2d2a2e
    editbold = #a9dc76;#2d2a2e
    editmarked = #fcfcfa;#403e41
    editwhitespace = #5b595c;#2d2a2e
    editlinestate = #939293;#403e41
    bookmark = #fcfcfa;#ff6188
    bookmarkfound = #2d2a2e;#a9dc76
    editrightmargin = #403e41;#2d2a2e
#    editbg =
#    editframe =
    editframeactive = #78dce8;
    editframedrag = #ff6188;

[viewer]
    _default_ = #fcfcfa;#2d2a2e
    viewbold = #a9dc76;#2d2a2e
    viewunderline = #78dce8;#2d2a2e
    viewselected = #fcfcfa;#403e41

[diffviewer]
    added = #a9dc76;#2d2a2e
    changedline = #78dce8;#2d2a2e
    changednew = #fc9867;#2d2a2e
    changed = #ffd866;#2d2a2e
    removed = #ff6188;#2d2a2e
    error = #fcfcfa;#ff6188

[widget-panel]
    sort-up-char = ↑
    sort-down-char = ↓
    hiddenfiles-show-char = ⋅
    hiddenfiles-hide-char = •
    history-prev-item-char = «
    history-next-item-char = »
    history-show-list-char = ^
    filename-scroll-left-char = «
    filename-scroll-right-char = »

[widget-editor]
    window-state-char = ↕
    window-close-char = ✕
