[skin]
    description = skin inspired by Total Commander
    truecolors = true

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ═
    dvert = ║
    dlefttop = ╔
    drighttop = ╗
    dleftbottom = ╚
    drightbottom = ╝
    dtopmiddle = ╤
    dbottommiddle = ╧
    dleftmiddle = ╟
    drightmiddle = ╢

[core]
    _default_ = #000000;#ffffff
    selected = #ffffff;#000080
    marked = #ff0000;#ffffff
    markselect = #ff0000;#000080
    gauge = #ffffff;#000080
    input = #000000;#ffffff
    inputunchanged = #808080;#ffffff
    inputmark = #ffffff;#000080
    disabled = #808080;#d4d0c8
    reverse = #ffffff;#000000
    commandlinemark = #ffffff;#000080
    header = #000000;#d4d0c8
    inputhistory = #000000;#ffffff
    commandhistory =
    shadow = #808080;#808080

[dialog]
    _default_ = #000000;#f0f0f0
    dfocus = #ffffff;#000080
    dhotnormal = #000080;#f0f0f0
    dhotfocus = #ffffff;#000080
    dtitle = #000000;#f0f0f0

[error]
    _default_ = #ffffff;#cc0000
    errdfocus = #000000;#f0f0f0
    errdhotnormal = #ffff00;#cc0000
    errdhotfocus = #ffff00;#f0f0f0
    errdtitle = #ffffff;#cc0000

[filehighlight]
    directory = #000080;
    executable = #008000;
    symlink = #808080;
    hardlink =
    stalelink = #cc0000;
    device = #800080;
    special = #008080;
    core = #cc0000;
    temp = #808080;
    archive = #800080;
    doc = #000080;
    source = #008000;
    media = #808000;
    graph = #008080;
    database = #800000;

[menu]
    _default_ = #000000;#d4d0c8
    menusel = #ffffff;#000080
    menuhot = #800000;#d4d0c8
    menuhotsel = #ffffff;#000080
    menuinactive = #808080;#d4d0c8

[popupmenu]
    _default_ = #000000;#f0f0f0
    menusel = #ffffff;#000080
    menutitle = #000000;#f0f0f0

[buttonbar]
    hotkey = #000080;#d4d0c8
    button = #000000;#d4d0c8

[statusbar]
    _default_ = #000000;#d4d0c8

[help]
    _default_ = #000000;#ffffff
    helpitalic = #800000;#ffffff
    helpbold = #000080;#ffffff
    helplink = #0000ff;#ffffff
    helpslink = #ffffff;#000080
    helptitle = #000080;#ffffff

[editor]
    _default_ = #000000;#ffffff
    editbold = #000080;#ffffff
    editmarked = #ffffff;#000080
    editwhitespace = #d4d0c8;#ffffff
    editlinestate = #808080;#f0f0f0
    bookmark = #ffffff;#cc0000
    bookmarkfound = #000000;#ffff00
    editrightmargin = #f0f0f0;#ffffff
#    editbg =
#    editframe =
    editframeactive = #000080;
    editframedrag = #808080;

[viewer]
    _default_ = #000000;#ffffff
    viewbold = #000080;#ffffff
    viewunderline = #800000;#ffffff
    viewselected = #ffffff;#000080

[diffviewer]
    added = #008000;#ffffff
    changedline = #000080;#ffffff
    changednew = #800080;#ffffff
    changed = #808000;#ffffff
    removed = #cc0000;#ffffff
    error = #ffffff;#cc0000

[widget-panel]
    sort-up-char = ↑
    sort-down-char = ↓
    hiddenfiles-show-char = ⋅
    hiddenfiles-hide-char = •
    history-prev-item-char = «
    history-next-item-char = »
    history-show-list-char = ^
    filename-scroll-left-char = «
    filename-scroll-right-char = »

[widget-editor]
    window-state-char = ↕
    window-close-char = ✕
