[skin]
    description = skin inspired by Borland Turbo Pascal IDE
    truecolors = true

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ═
    dvert = ║
    dlefttop = ╔
    drighttop = ╗
    dleftbottom = ╚
    drightbottom = ╝
    dtopmiddle = ╤
    dbottommiddle = ╧
    dleftmiddle = ╟
    drightmiddle = ╢

[core]
    _default_ = #ffff55;#0000aa
    selected = #ffff55;#00aaaa
    marked = #55ff55;#0000aa
    markselect = #55ff55;#00aaaa
    gauge = #ffffff;#000000
    input = #ffffff;#0000aa
    inputunchanged = #aaaaaa;#0000aa
    inputmark = #000000;#00aaaa
    disabled = #555555;#0000aa
    reverse = #0000aa;#ffff55
    commandlinemark = #000000;#00aaaa
    header = #ffffff;#0000aa
    inputhistory = #ffffff;#0000aa
    commandhistory =
    shadow = #000000;#000000

[dialog]
    _default_ = #000000;#aaaaaa
    dfocus = #ffffff;#00aa00
    dhotnormal = #ffff55;#aaaaaa
    dhotfocus = #ffff55;#00aa00
    dtitle = #000000;#aaaaaa

[error]
    _default_ = #ffffff;#aa0000
    errdfocus = #000000;#aaaaaa
    errdhotnormal = #ffff55;#aa0000
    errdhotfocus = #ffff55;#aaaaaa
    errdtitle = #ffff55;#aa0000

[filehighlight]
    directory = #ffffff;
    executable = #55ff55;
    symlink = #aaaaaa;
    hardlink =
    stalelink = #ff5555;
    device = #ff55ff;
    special = #55ffff;
    core = #ff5555;
    temp = #aaaaaa;
    archive = #ff55ff;
    doc = #55ffff;
    source = #55ff55;
    media = #aa5500;
    graph = #5555ff;
    database = #ff5555;

[menu]
    _default_ = #000000;#aaaaaa
    menusel = #000000;#00aa00
    menuhot = #aa0000;#aaaaaa
    menuhotsel = #aa0000;#00aa00
    menuinactive = #555555;#aaaaaa

[popupmenu]
    _default_ = #000000;#aaaaaa
    menusel = #000000;#00aa00
    menutitle = #000000;#aaaaaa

[buttonbar]
    hotkey = #aa0000;#aaaaaa
    button = #000000;#aaaaaa

[statusbar]
    _default_ = #000000;#aaaaaa

[help]
    _default_ = #000000;#00aaaa
    helpitalic = #ffff55;#00aaaa
    helpbold = #ffffff;#00aaaa
    helplink = #ffffff;#0000aa
    helpslink = #ffff55;#00aa00
    helptitle = #000000;#00aaaa

[editor]
    _default_ = #ffff55;#0000aa
    editbold = #ffffff;#0000aa
    editmarked = #000000;#00aaaa
    editwhitespace = #555555;#0000aa
    editlinestate = #aaaaaa;#00aaaa
    bookmark = #ffffff;#aa0000
    bookmarkfound = #000000;#55ff55
    editrightmargin = #555555;#0000aa
#    editbg =
#    editframe =
    editframeactive = #ffffff;
    editframedrag = #55ffff;

[viewer]
    _default_ = #ffff55;#0000aa
    viewbold = #ffffff;#0000aa
    viewunderline = #55ffff;#0000aa
    viewselected = #000000;#00aaaa

[diffviewer]
    added = #55ff55;#0000aa
    changedline = #ffffff;#0000aa
    changednew = #55ffff;#0000aa
    changed = #ffff55;#0000aa
    removed = #ff5555;#0000aa
    error = #ffffff;#aa0000

[widget-panel]
    sort-up-char = ↑
    sort-down-char = ↓
    hiddenfiles-show-char = ⋅
    hiddenfiles-hide-char = •
    history-prev-item-char = «
    history-next-item-char = »
    history-show-list-char = ^
    filename-scroll-left-char = «
    filename-scroll-right-char = »

[widget-editor]
    window-state-char = ↕
    window-close-char = ✕
