[skin]
    description = skin inspired by Volkov Commander
    truecolors = true

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ═
    dvert = ║
    dlefttop = ╔
    drighttop = ╗
    dleftbottom = ╚
    drightbottom = ╝
    dtopmiddle = ╤
    dbottommiddle = ╧
    dleftmiddle = ╟
    drightmiddle = ╢

[core]
    _default_ = #55ffff;#0000aa
    selected = #000000;#00aaaa
    marked = #ffff55;#0000aa
    markselect = #ffff55;#00aaaa
    gauge = #ffffff;#000000
    #input = #ffffff;#000000
    #inputunchanged = #c0c0c0;#00aaaa
    input = #000000;#00aaaa
    inputunchanged = #c0c0c0;#00aaaa
    inputmark = #00aaaa;#000000
    disabled = #808080;#aaaaaa
    reverse = #000000;#00aaaa
    commandlinemark = #000000;#c0c0c0
    header = #ffff55;#0000aa
    inputhistory = #0000aa;#00aaaa
    commandhistory =
    shadow = #00aaaa;#000000

[dialog]
    _default_ = #000000;#aaaaaa
    dfocus = #000000;#00aaaa
    dhotnormal = #ffff00;#aaaaaa
    dhotfocus = #ffff00;#00aaaa
    dtitle = #000000;#aaaaaa
    #_default_ = #ffffff;#00aaaa
    #dfocus = #000000;#808080
    #dhotnormal = #ffff00;#00aaaa
    #dhotfocus = #ffff00;#808080
    #dtitle = #000000;#00aaaa

[error]
    _default_ = #ffffff;#aa0000
    errdfocus = #000000;#c0c0c0
    errdhotnormal = #ffff55;#aa0000
    errdhotfocus = #ffff55;#c0c0c0
    errdtitle = #ffff55;#aa0000

[filehighlight]
    directory = #ffffff;
    executable = #55ff55;
    symlink = #c0c0c0;
    hardlink =
    stalelink = #ff5555;
    device = #ff55ff;
    special = #00ffbb;
    core = #aa0000;
    temp = #808080;
    archive = #ff55ff;
    doc = #aa5500;
    source = #00aaaa;
    media = #00aa00;
    graph = #55ffff;
    database = #ff5555;

[menu]
    _default_ = #ffffff;#00aaaa
    menusel = #ffffff;#000000
    menuhot = #ffff55;#00aaaa
    menuhotsel = #ffff55;#000000
    menuinactive = #000000;#00aaaa

[popupmenu]
    _default_ = #ffffff;#00aaaa
    menusel = #ffffff;#000000
    menutitle = #ffffff;#00aaaa

[buttonbar]
    hotkey = #aaaaaa;#000000
    button = #000000;#00aaaa

[statusbar]
    _default_ = #000000;#00aaaa

[help]
    _default_ = #000000;#00aaaa
    helpitalic = #ffff55;#00aaaa
    helpbold = #ffffff;#00aaaa
    helplink = #000000;#aaaaaa
    helpslink = #ffff55;#000000
    helptitle = #0000aa;#c0c0c0

[editor]
    _default_ = #55ffff;#0000aa
    editbold = #ffff55;#00aa00
    editmarked = #000000;#00aaaa
    editwhitespace = #5555ff;#0000aa
    editlinestate = #ffffff;#00aaaa
    bookmark = #ffffff;#aa0000
    bookmarkfound = #000000;#00aa00
    editrightmargin = #5555ff;#000000
#    editbg =
#    editframe =
    editframeactive = #c0c0c0;
    editframedrag = #00aaaa;

[viewer]
    _default_ = #55ffff;#0000aa
    viewbold = #ffff55;#0000aa
    viewunderline = #ff5555;#0000aa
    viewselected = #ffff55;#00aaaa

[diffviewer]
    added = #ffffff;#00aa00
    changedline = #0000aa;#00aaaa
    changednew = #aa0000;#00aaaa
    changed = #ffffff;#00aaaa
    removed = #ffffff;#aa0000
    error = #aa0000;#c0c0c0

[widget-panel]
    sort-up-char = ↑
    sort-down-char = ↓
    hiddenfiles-show-char = ⋅
    hiddenfiles-hide-char = •
    history-prev-item-char = «
    history-next-item-char = »
    history-show-list-char = ^
    filename-scroll-left-char = «
    filename-scroll-right-char = »

[widget-editor]
    window-state-char = ↕
    window-close-char = ✕
