[skin]
    description = VS Code Dark+ color scheme
    truecolors = true

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ═
    dvert = ║
    dlefttop = ╔
    drighttop = ╗
    dleftbottom = ╚
    drightbottom = ╝
    dtopmiddle = ╤
    dbottommiddle = ╧
    dleftmiddle = ╟
    drightmiddle = ╢

[core]
    _default_ = #d4d4d4;#1e1e1e
    selected = #d4d4d4;#094771
    marked = #dcdcaa;#1e1e1e
    markselect = #dcdcaa;#094771
    gauge = #ffffff;#007acc
    input = #d4d4d4;#3c3c3c
    inputunchanged = #a6a6a6;#3c3c3c
    inputmark = #ffffff;#264f78
    disabled = #808080;#1e1e1e
    reverse = #1e1e1e;#d4d4d4
    commandlinemark = #ffffff;#264f78
    header = #569cd6;#1e1e1e
    inputhistory = #d4d4d4;#3c3c3c
    commandhistory =
    shadow = #000000;#000000

[dialog]
    _default_ = #cccccc;#252526
    dfocus = #ffffff;#094771
    dhotnormal = #569cd6;#252526
    dhotfocus = #ffffff;#094771
    dtitle = #cccccc;#252526

[error]
    _default_ = #ffffff;#f44747
    errdfocus = #d4d4d4;#3c3c3c
    errdhotnormal = #dcdcaa;#f44747
    errdhotfocus = #dcdcaa;#3c3c3c
    errdtitle = #dcdcaa;#f44747

[filehighlight]
    directory = #569cd6;
    executable = #4ec9b0;
    symlink = #808080;
    hardlink =
    stalelink = #f44747;
    device = #d7ba7d;
    special = #c586c0;
    core = #f44747;
    temp = #808080;
    archive = #c586c0;
    doc = #ce9178;
    source = #dcdcaa;
    media = #c586c0;
    graph = #9cdcfe;
    database = #b5cea8;

[menu]
    _default_ = #cccccc;#252526
    menusel = #ffffff;#094771
    menuhot = #569cd6;#252526
    menuhotsel = #569cd6;#094771
    menuinactive = #808080;#252526

[popupmenu]
    _default_ = #cccccc;#252526
    menusel = #ffffff;#094771
    menutitle = #569cd6;#252526

[buttonbar]
    hotkey = #ffffff;#007acc
    button = #ffffff;#007acc

[statusbar]
    _default_ = #d4d4d4;#252526

[help]
    _default_ = #cccccc;#252526
    helpitalic = #ce9178;#252526
    helpbold = #d4d4d4;#252526
    helplink = #569cd6;#252526
    helpslink = #ffffff;#094771
    helptitle = #569cd6;#252526

[editor]
    _default_ = #d4d4d4;#1e1e1e
    editbold = #dcdcaa;#1e1e1e
    editmarked = #d4d4d4;#264f78
    editwhitespace = #404040;#1e1e1e
    editlinestate = #808080;#252526
    bookmark = #ffffff;#f44747
    bookmarkfound = #1e1e1e;#4ec9b0
    editrightmargin = #303031;#1e1e1e
#    editbg =
#    editframe =
    editframeactive = #569cd6;
    editframedrag = #007acc;

[viewer]
    _default_ = #d4d4d4;#1e1e1e
    viewbold = #dcdcaa;#1e1e1e
    viewunderline = #569cd6;#1e1e1e
    viewselected = #d4d4d4;#264f78

[diffviewer]
    added = #4ec9b0;#1e1e1e
    changedline = #569cd6;#1e1e1e
    changednew = #ce9178;#1e1e1e
    changed = #dcdcaa;#1e1e1e
    removed = #f44747;#1e1e1e
    error = #ffffff;#f44747

[widget-panel]
    sort-up-char = ↑
    sort-down-char = ↓
    hiddenfiles-show-char = ⋅
    hiddenfiles-hide-char = •
    history-prev-item-char = «
    history-next-item-char = »
    history-show-list-char = ^
    filename-scroll-left-char = «
    filename-scroll-right-char = »

[widget-editor]
    window-state-char = ↕
    window-close-char = ✕
