[skin]
    description = VS Code Light+ color scheme
    truecolors = true

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ═
    dvert = ║
    dlefttop = ╔
    drighttop = ╗
    dleftbottom = ╚
    drightbottom = ╝
    dtopmiddle = ╤
    dbottommiddle = ╧
    dleftmiddle = ╟
    drightmiddle = ╢

[core]
    _default_ = #000000;#ffffff
    selected = #ffffff;#0060c0
    marked = #af00db;#ffffff
    markselect = #af00db;#0060c0
    gauge = #ffffff;#007acc
    input = #000000;#ffffff
    inputunchanged = #767676;#ffffff
    inputmark = #000000;#add6ff
    disabled = #919191;#ffffff
    reverse = #ffffff;#000000
    commandlinemark = #000000;#add6ff
    header = #0000ff;#ffffff
    inputhistory = #000000;#ffffff
    commandhistory =
    shadow = #d4d4d4;#d4d4d4

[dialog]
    _default_ = #000000;#f3f3f3
    dfocus = #ffffff;#0078d4
    dhotnormal = #0000ff;#f3f3f3
    dhotfocus = #ffffff;#0078d4
    dtitle = #000000;#f3f3f3

[error]
    _default_ = #ffffff;#cd3131
    errdfocus = #000000;#f3f3f3
    errdhotnormal = #795e26;#cd3131
    errdhotfocus = #795e26;#f3f3f3
    errdtitle = #ffffff;#cd3131

[filehighlight]
    directory = #0000ff;
    executable = #267f99;
    symlink = #767676;
    hardlink =
    stalelink = #cd3131;
    device = #795e26;
    special = #af00db;
    core = #cd3131;
    temp = #767676;
    archive = #af00db;
    doc = #a31515;
    source = #795e26;
    media = #af00db;
    graph = #001080;
    database = #098658;

[menu]
    _default_ = #000000;#f3f3f3
    menusel = #ffffff;#0078d4
    menuhot = #0000ff;#f3f3f3
    menuhotsel = #ffffff;#0078d4
    menuinactive = #919191;#f3f3f3

[popupmenu]
    _default_ = #000000;#f3f3f3
    menusel = #ffffff;#0078d4
    menutitle = #0000ff;#f3f3f3

[buttonbar]
    hotkey = #ffffff;#007acc
    button = #ffffff;#007acc

[statusbar]
    _default_ = #000000;#f3f3f3

[help]
    _default_ = #000000;#f3f3f3
    helpitalic = #a31515;#f3f3f3
    helpbold = #000000;#f3f3f3
    helplink = #0000ff;#f3f3f3
    helpslink = #ffffff;#0078d4
    helptitle = #0000ff;#f3f3f3

[editor]
    _default_ = #000000;#ffffff
    editbold = #795e26;#ffffff
    editmarked = #000000;#add6ff
    editwhitespace = #d3d3d3;#ffffff
    editlinestate = #767676;#f3f3f3
    bookmark = #ffffff;#cd3131
    bookmarkfound = #000000;#98d798
    editrightmargin = #f3f3f3;#ffffff
#    editbg =
#    editframe =
    editframeactive = #0000ff;
    editframedrag = #007acc;

[viewer]
    _default_ = #000000;#ffffff
    viewbold = #795e26;#ffffff
    viewunderline = #0000ff;#ffffff
    viewselected = #000000;#add6ff

[diffviewer]
    added = #098658;#ffffff
    changedline = #0000ff;#ffffff
    changednew = #0451a5;#ffffff
    changed = #795e26;#ffffff
    removed = #cd3131;#ffffff
    error = #ffffff;#cd3131

[widget-panel]
    sort-up-char = ↑
    sort-down-char = ↓
    hiddenfiles-show-char = ⋅
    hiddenfiles-hide-char = •
    history-prev-item-char = «
    history-next-item-char = »
    history-show-list-char = ^
    filename-scroll-left-char = «
    filename-scroll-right-char = »

[widget-editor]
    window-state-char = ↕
    window-close-char = ✕
