[skin]
    description = skin inspired by Windows XP Luna Blue
    truecolors = true

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ═
    dvert = ║
    dlefttop = ╔
    drighttop = ╗
    dleftbottom = ╚
    drightbottom = ╝
    dtopmiddle = ╤
    dbottommiddle = ╧
    dleftmiddle = ╟
    drightmiddle = ╢

[core]
    _default_ = #000000;#ffffff
    selected = #ffffff;#316ac5
    marked = #0054e3;#ffffff
    markselect = #ffffff;#0054e3
    gauge = #ffffff;#316ac5
    input = #000000;#ffffff
    inputunchanged = #aca899;#ffffff
    inputmark = #ffffff;#316ac5
    disabled = #aca899;#ece9d8
    reverse = #ffffff;#000000
    commandlinemark = #ffffff;#316ac5
    header = #000000;#ece9d8
    inputhistory = #000000;#ffffff
    commandhistory =
    shadow = #aca899;#aca899

[dialog]
    _default_ = #000000;#ece9d8
    dfocus = #ffffff;#316ac5
    dhotnormal = #0054e3;#ece9d8
    dhotfocus = #ffffff;#316ac5
    dtitle = #000000;#ece9d8

[error]
    _default_ = #ffffff;#c80000
    errdfocus = #000000;#ece9d8
    errdhotnormal = #ffff00;#c80000
    errdhotfocus = #ffff00;#ece9d8
    errdtitle = #ffffff;#c80000

[filehighlight]
    directory = #316ac5;
    executable = #3c9a41;
    symlink = #aca899;
    hardlink =
    stalelink = #c80000;
    device = #808000;
    special = #808000;
    core = #c80000;
    temp = #aca899;
    archive = #800080;
    doc = #0054e3;
    source = #3c9a41;
    media = #800080;
    graph = #316ac5;
    database = #008080;

[menu]
    _default_ = #000000;#ece9d8
    menusel = #ffffff;#316ac5
    menuhot = #0054e3;#ece9d8
    menuhotsel = #ffffff;#316ac5
    menuinactive = #aca899;#ece9d8

[popupmenu]
    _default_ = #000000;#ffffff
    menusel = #ffffff;#316ac5
    menutitle = #000000;#ffffff

[buttonbar]
    hotkey = #ffffff;#245edb
    button = #ffffff;#245edb

[statusbar]
    _default_ = #000000;#ece9d8

[help]
    _default_ = #000000;#ffffff
    helpitalic = #800000;#ffffff
    helpbold = #000000;#ffffff
    helplink = #0066cc;#ffffff
    helpslink = #ffffff;#316ac5
    helptitle = #316ac5;#ffffff

[editor]
    _default_ = #000000;#ffffff
    editbold = #0054e3;#ffffff
    editmarked = #ffffff;#316ac5
    editwhitespace = #ece9d8;#ffffff
    editlinestate = #aca899;#ece9d8
    bookmark = #ffffff;#c80000
    bookmarkfound = #000000;#ffff00
    editrightmargin = #ece9d8;#ffffff
#    editbg =
#    editframe =
    editframeactive = #316ac5;
    editframedrag = #aca899;

[viewer]
    _default_ = #000000;#ffffff
    viewbold = #0054e3;#ffffff
    viewunderline = #0066cc;#ffffff
    viewselected = #ffffff;#316ac5

[diffviewer]
    added = #3c9a41;#ffffff
    changedline = #316ac5;#ffffff
    changednew = #0054e3;#ffffff
    changed = #808000;#ffffff
    removed = #c80000;#ffffff
    error = #ffffff;#c80000

[widget-panel]
    sort-up-char = ↑
    sort-down-char = ↓
    hiddenfiles-show-char = ⋅
    hiddenfiles-hide-char = •
    history-prev-item-char = «
    history-next-item-char = »
    history-show-list-char = ^
    filename-scroll-left-char = «
    filename-scroll-right-char = »

[widget-editor]
    window-state-char = ↕
    window-close-char = ✕
